word = input("Give me a word!: ")
print(word)
second_word = input("Give me a second word!: ")
print(second_word)
favorite_number = int(input("Great now your favorite number?: "))
print(favorite_number)
second_favorite_number = int(input("Great now your second-favorite number?: "))
print(second_favorite_number)
print("Whew! wasn't that fun? ")
